title: Brian H. Castelhano Copywriter
description: Textos que vendem. Estratégias que convertem.
baseurl: "" # deixe vazio se for no root do domínio
url: "https://seuusuario.github.io" # substitua pela sua url

collections:
  projects:
    output: true

plugins: []
